import React from "react";
import Image from "next/image";
import Features from "@/components/Features";
import Head from "next/head";

export default function about() {
  return (
    <>
      <Head>
        <title>Solbiler ApS | Om os</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className=" bg-slate-100">
        <section>
          <div className="md:flex max-w-[1280px] mx-auto py-4 md:space-x-6 md:py-20">
            <div className="flex flex-col w-screen px-2 text-left space-y-4">
              <h1 className=" text-4xl font-bold">Om os</h1>
              <h2 className=" text-lg text-gray-800 tracking-wide ">
                Solbiler ApS er en familiedrevet virksomhed, der har leveret
                pålidelig biludlejning i mere end 30 år. Virksomheden blev
                grundlagt af Lis og Per, som stadig er involveret i den daglige
                drift. Virksomheden har en bred vifte af kunder, lige fra
                forretningsfolk til turister og alle, der har brug for at leje
                en bil.
                <br />
                <br />
                Reservation af biler er nemt og bekvemt ved at ringe til
                virksomheden eller via vores hjemmeside. Her finder du også
                vores komplette udvalg af lejebiler og yderligere oplysninger om
                virksomheden og vores service.
                <br />
                <br />
                Solbiler ApS er mere end bare en biludlejningsvirksomhed - det
                er en virksomhed, der vægter en god kundeoplevelse højt og tager
                sig af alle kunders transportbehov. Med hjælp fra Lis og Pers to
                døtre og deres svigersønner kan du altid forvente en personlig
                og professionel service fra Solbiler ApS.
              </h2>
            </div>
            <Image
              src="/firma.png"
              alt="image of company"
              width={550}
              height={500}
              className=" my-10"
            />
          </div>
          <div>
            <Features />
          </div>
        </section>
      </div>
    </>
  );
}
