import Head from "next/head";
import { Inter } from "@next/font/google";
import Hero from "@/components/Hero";
import CarSection from "@/components/CarSection";

const inter = Inter({
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Solbiler ApS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className={inter.className}>
        <div className=" w-100% bg-gray-200 text-sm py-1 flex justify-center text-gray-900">
          <p>
            SPAR NU - Priserne på vores mellemklasse biler har aldrig været
            lavere!
          </p>
        </div>
        <Hero />
        <CarSection />
      </main>
    </>
  );
}
