import React from "react";
import Link from "next/link";
import Head from "next/head";
import SuccessMSG from "@/components/SuccessMSG";
import { useEffect, useState } from "react";

export default function Select() {
  const [dateData, setDateData] = useState("");
  const [price, setPrice] = useState(0);
  const [finalPrice, setFinalPrice] = useState(0);
  const [car, setCar] = useState("");
  const [dates, setDates] = useState("");
  const [afhentning, setAfhentning] = useState("");
  const [aflevering, setAflevering] = useState("");
  const [dayAmount, setDayAmount] = useState(0);
  const [barnesæde1, setBarnesaede1] = useState("");
  const [barnesæde2, setBarnesaede2] = useState("");
  const [vejhjælp, setVejhjaelp] = useState("");
  const [gps, setGPS] = useState("");
  const [lift, setLift] = useState("");
  const [snekæder, setSnekaeder] = useState("");

  useEffect(() => {
    const dateData = sessionStorage.getItem("date");
    const price = parseInt(sessionStorage.getItem("price"));
    const finalPrice = sessionStorage.getItem("total");
    const car = sessionStorage.getItem("car");
    const dates = JSON.parse(dateData);
    const afhentning = new Date(dates.afhentning);
    const aflevering = new Date(dates.aflevering);
    const dayAmount = Math.round((aflevering - afhentning) / 86400000);
    const barnesæde1 = sessionStorage.getItem("Barnesæde (1-4 år)");
    const barnesæde2 = sessionStorage.getItem("Barnesæde (5-12 år)");
    const vejhjælp = sessionStorage.getItem("Vejhjælp");
    const gps = sessionStorage.getItem("GPS navigation");
    const lift = sessionStorage.getItem("Lift-net (0-1 år)");
    const snekæder = sessionStorage.getItem("Snekæder");

    setDateData(dateData);
    setPrice(price);
    setFinalPrice(finalPrice);
    setCar(car);
    setDates(dates);
    setAfhentning(afhentning);
    setAflevering(aflevering);
    setDayAmount(dayAmount);
    setBarnesaede1(barnesæde1);
    setBarnesaede2(barnesæde2);
    setVejhjaelp(vejhjælp);
    setGPS(gps);
    setLift(lift);
    setSnekaeder(snekæder);
  }, []);

  return (
    <>
      <Head>
        <title>Solbiler ApS | Check ud</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className=" w-full bg-slate-50 py-32">
        <Link
          href="/oplysninger"
          className=" flex text-gray-700 text-4xl  md:text-2xl items-center ml-2 xl:translate-x-[8rem] 2xl:translate-x-[12rem] space-x-2 hover:text-gray-500 transition-all print:hidden"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="currentColor"
            className="w-10 h-10 md:w-7 md:h-7"
          >
            <path
              fillRule="evenodd"
              d="M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25zm-4.28 9.22a.75.75 0 000 1.06l3 3a.75.75 0 101.06-1.06l-1.72-1.72h5.69a.75.75 0 000-1.5h-5.69l1.72-1.72a.75.75 0 00-1.06-1.06l-3 3z"
              clipRule="evenodd"
            />
          </svg>
          <p>Gå tilbage</p>
        </Link>
        <div className=" flex flex-col md:flex-row max-w-[1200px] mx-auto items-center md:items-start py-4 px-2 gap-8">
          <div className=" w-[90%] md:w-1/3 bg-slate-200 rounded-sm py-8 px-4 space-y-10">
            <h2 className=" text-4xl md:text-2xl font-medium">Dine valg</h2>
            <div className=" space-y-2">
              <h2 className=" text-3xl md:text-xl  font-medium">
                {car ?? "loading..."}
              </h2>
              <p className=" text-lg md:text-base">
                Aflevering: {new Date(dates.afhentning).toLocaleDateString()}{" "}
              </p>
              <p className=" text-lg md:text-base">
                Afhentning: {new Date(dates.aflevering).toLocaleDateString()}{" "}
              </p>
              <p className=" text-lg md:text-base">Antal dage: {dayAmount}</p>
            </div>
            <div className=" space-y-2">
              <h2 className=" text-3xl md:text-xl  font-medium">Tilvalg</h2>
              {barnesæde1 ? (
                <p className="text-lg md:text-base">{barnesæde1} kr.</p>
              ) : null}
              {barnesæde2 ? (
                <p className="text-lg md:text-base">{barnesæde2} kr.</p>
              ) : null}
              {vejhjælp ? (
                <p className="text-lg md:text-base">{vejhjælp} kr.</p>
              ) : null}
              {gps ? <p className="text-lg md:text-base">{gps} kr.</p> : null}
              {lift ? <p className="text-lg md:text-base">{lift} kr.</p> : null}
              {snekæder ? (
                <p className="text-lg md:text-base">{snekæder} kr.</p>
              ) : null}
            </div>

            <div>
              <h2 className=" font-semibold text-2xl">
                Pris i alt {finalPrice} kr.
              </h2>
              <p>inkl. moms</p>
            </div>
          </div>
          <div className=" w-[90%] flex flex-col gap-4">
            <div className="w-full bg-blue-100 rounded-sm py-8 px-4 flex flex-col item-center ">
              <SuccessMSG />
            </div>
            <div className=" bg-blue-500 text-white w-full flex justify-between items-center px-4 py-4 rounded-sm print:hidden">
              <div>
                <h2 className=" text-xl font-semibold">
                  TOTAL {finalPrice} kr.
                </h2>
                <p className=" text-gray-100 ">inkl. moms</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
